# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='names',
            new_name='name',
        ),
    ]
